# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the elixir code generator program.
# Do not edit the class manually.

defmodule GoogleApi.AnalyticsReporting.V4.Model.PageviewData do
  @moduledoc """
  Represents details collected when the visitor views a page.

  ## Attributes

  *   `pagePath` (*type:* `String.t`, *default:* `nil`) - The URL of the page that the visitor viewed.
  *   `pageTitle` (*type:* `String.t`, *default:* `nil`) - The title of the page that the visitor viewed.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :pagePath => String.t(),
          :pageTitle => String.t()
        }

  field(:pagePath)
  field(:pageTitle)
end

defimpl Poison.Decoder, for: GoogleApi.AnalyticsReporting.V4.Model.PageviewData do
  def decode(value, options) do
    GoogleApi.AnalyticsReporting.V4.Model.PageviewData.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.AnalyticsReporting.V4.Model.PageviewData do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
