# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.AIPlatform.V1.Model.GoogleCloudAiplatformV1CreateDeploymentResourcePoolRequest do
  @moduledoc """
  Request message for CreateDeploymentResourcePool method.

  ## Attributes

  *   `deploymentResourcePool` (*type:* `GoogleApi.AIPlatform.V1.Model.GoogleCloudAiplatformV1DeploymentResourcePool.t`, *default:* `nil`) - Required. The DeploymentResourcePool to create.
  *   `deploymentResourcePoolId` (*type:* `String.t`, *default:* `nil`) - Required. The ID to use for the DeploymentResourcePool, which will become the final component of the DeploymentResourcePool's resource name. The maximum length is 63 characters, and valid characters are `/^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$/`.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :deploymentResourcePool =>
            GoogleApi.AIPlatform.V1.Model.GoogleCloudAiplatformV1DeploymentResourcePool.t() | nil,
          :deploymentResourcePoolId => String.t() | nil
        }

  field(:deploymentResourcePool,
    as: GoogleApi.AIPlatform.V1.Model.GoogleCloudAiplatformV1DeploymentResourcePool
  )

  field(:deploymentResourcePoolId)
end

defimpl Poison.Decoder,
  for: GoogleApi.AIPlatform.V1.Model.GoogleCloudAiplatformV1CreateDeploymentResourcePoolRequest do
  def decode(value, options) do
    GoogleApi.AIPlatform.V1.Model.GoogleCloudAiplatformV1CreateDeploymentResourcePoolRequest.decode(
      value,
      options
    )
  end
end

defimpl Poison.Encoder,
  for: GoogleApi.AIPlatform.V1.Model.GoogleCloudAiplatformV1CreateDeploymentResourcePoolRequest do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
