# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.VectorTile.V1.Model.RoadInfo do
  @moduledoc """
  Extra metadata relating to roads.

  ## Attributes

  *   `isPrivate` (*type:* `boolean()`, *default:* `nil`) - Road has signage discouraging or prohibiting use by the general public. E.g., roads with signs that say "Private", or "No trespassing."
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :isPrivate => boolean()
        }

  field(:isPrivate)
end

defimpl Poison.Decoder, for: GoogleApi.VectorTile.V1.Model.RoadInfo do
  def decode(value, options) do
    GoogleApi.VectorTile.V1.Model.RoadInfo.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.VectorTile.V1.Model.RoadInfo do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
