# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.Speech.V2.Model.OperationMetadata do
  @moduledoc """
  Represents the metadata of a long-running operation.

  ## Attributes
  
  *   `batchRecognizeMetadata` (*type:* `GoogleApi.Speech.V2.Model.BatchRecognizeMetadata.t`, *default:* `nil`) - Metadata specific to the BatchRecognize method.
  *   `batchRecognizeRequest` (*type:* `GoogleApi.Speech.V2.Model.BatchRecognizeRequest.t`, *default:* `nil`) - The BatchRecognizeRequest that spawned the Operation.
  *   `createCustomClassRequest` (*type:* `GoogleApi.Speech.V2.Model.CreateCustomClassRequest.t`, *default:* `nil`) - The CreateCustomClassRequest that spawned the Operation.
  *   `createPhraseSetRequest` (*type:* `GoogleApi.Speech.V2.Model.CreatePhraseSetRequest.t`, *default:* `nil`) - The CreatePhraseSetRequest that spawned the Operation.
  *   `createRecognizerRequest` (*type:* `GoogleApi.Speech.V2.Model.CreateRecognizerRequest.t`, *default:* `nil`) - The CreateRecognizerRequest that spawned the Operation.
  *   `createTime` (*type:* `DateTime.t`, *default:* `nil`) - The time the operation was created.
  *   `deleteCustomClassRequest` (*type:* `GoogleApi.Speech.V2.Model.DeleteCustomClassRequest.t`, *default:* `nil`) - The DeleteCustomClassRequest that spawned the Operation.
  *   `deletePhraseSetRequest` (*type:* `GoogleApi.Speech.V2.Model.DeletePhraseSetRequest.t`, *default:* `nil`) - The DeletePhraseSetRequest that spawned the Operation.
  *   `deleteRecognizerRequest` (*type:* `GoogleApi.Speech.V2.Model.DeleteRecognizerRequest.t`, *default:* `nil`) - The DeleteRecognizerRequest that spawned the Operation.
  *   `kmsKeyName` (*type:* `String.t`, *default:* `nil`) - The [KMS key name](https://cloud.google.com/kms/docs/resource-hierarchy#keys) with which the content of the Operation is encrypted. The expected format is `projects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}`.
  *   `kmsKeyVersionName` (*type:* `String.t`, *default:* `nil`) - The [KMS key version name](https://cloud.google.com/kms/docs/resource-hierarchy#key_versions) with which content of the Operation is encrypted. The expected format is `projects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}/cryptoKeyVersions/{crypto_key_version}`.
  *   `method` (*type:* `String.t`, *default:* `nil`) - The method that triggered the operation.
  *   `progressPercent` (*type:* `integer()`, *default:* `nil`) - The percent progress of the Operation. Values can range from 0-100. If the value is 100, then the operation is finished.
  *   `resource` (*type:* `String.t`, *default:* `nil`) - The resource path for the target of the operation.
  *   `undeleteCustomClassRequest` (*type:* `GoogleApi.Speech.V2.Model.UndeleteCustomClassRequest.t`, *default:* `nil`) - The UndeleteCustomClassRequest that spawned the Operation.
  *   `undeletePhraseSetRequest` (*type:* `GoogleApi.Speech.V2.Model.UndeletePhraseSetRequest.t`, *default:* `nil`) - The UndeletePhraseSetRequest that spawned the Operation.
  *   `undeleteRecognizerRequest` (*type:* `GoogleApi.Speech.V2.Model.UndeleteRecognizerRequest.t`, *default:* `nil`) - The UndeleteRecognizerRequest that spawned the Operation.
  *   `updateConfigRequest` (*type:* `GoogleApi.Speech.V2.Model.UpdateConfigRequest.t`, *default:* `nil`) - The UpdateConfigRequest that spawned the Operation.
  *   `updateCustomClassRequest` (*type:* `GoogleApi.Speech.V2.Model.UpdateCustomClassRequest.t`, *default:* `nil`) - The UpdateCustomClassRequest that spawned the Operation.
  *   `updatePhraseSetRequest` (*type:* `GoogleApi.Speech.V2.Model.UpdatePhraseSetRequest.t`, *default:* `nil`) - The UpdatePhraseSetRequest that spawned the Operation.
  *   `updateRecognizerRequest` (*type:* `GoogleApi.Speech.V2.Model.UpdateRecognizerRequest.t`, *default:* `nil`) - The UpdateRecognizerRequest that spawned the Operation.
  *   `updateTime` (*type:* `DateTime.t`, *default:* `nil`) - The time the operation was last updated.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
    
      :"batchRecognizeMetadata" => GoogleApi.Speech.V2.Model.BatchRecognizeMetadata.t | nil,
    
      :"batchRecognizeRequest" => GoogleApi.Speech.V2.Model.BatchRecognizeRequest.t | nil,
    
      :"createCustomClassRequest" => GoogleApi.Speech.V2.Model.CreateCustomClassRequest.t | nil,
    
      :"createPhraseSetRequest" => GoogleApi.Speech.V2.Model.CreatePhraseSetRequest.t | nil,
    
      :"createRecognizerRequest" => GoogleApi.Speech.V2.Model.CreateRecognizerRequest.t | nil,
    
      :"createTime" => DateTime.t | nil,
    
      :"deleteCustomClassRequest" => GoogleApi.Speech.V2.Model.DeleteCustomClassRequest.t | nil,
    
      :"deletePhraseSetRequest" => GoogleApi.Speech.V2.Model.DeletePhraseSetRequest.t | nil,
    
      :"deleteRecognizerRequest" => GoogleApi.Speech.V2.Model.DeleteRecognizerRequest.t | nil,
    
      :"kmsKeyName" => String.t | nil,
    
      :"kmsKeyVersionName" => String.t | nil,
    
      :"method" => String.t | nil,
    
      :"progressPercent" => integer() | nil,
    
      :"resource" => String.t | nil,
    
      :"undeleteCustomClassRequest" => GoogleApi.Speech.V2.Model.UndeleteCustomClassRequest.t | nil,
    
      :"undeletePhraseSetRequest" => GoogleApi.Speech.V2.Model.UndeletePhraseSetRequest.t | nil,
    
      :"undeleteRecognizerRequest" => GoogleApi.Speech.V2.Model.UndeleteRecognizerRequest.t | nil,
    
      :"updateConfigRequest" => GoogleApi.Speech.V2.Model.UpdateConfigRequest.t | nil,
    
      :"updateCustomClassRequest" => GoogleApi.Speech.V2.Model.UpdateCustomClassRequest.t | nil,
    
      :"updatePhraseSetRequest" => GoogleApi.Speech.V2.Model.UpdatePhraseSetRequest.t | nil,
    
      :"updateRecognizerRequest" => GoogleApi.Speech.V2.Model.UpdateRecognizerRequest.t | nil,
    
      :"updateTime" => DateTime.t | nil,
    
  }
  
  field(:"batchRecognizeMetadata", as: GoogleApi.Speech.V2.Model.BatchRecognizeMetadata)
  field(:"batchRecognizeRequest", as: GoogleApi.Speech.V2.Model.BatchRecognizeRequest)
  field(:"createCustomClassRequest", as: GoogleApi.Speech.V2.Model.CreateCustomClassRequest)
  field(:"createPhraseSetRequest", as: GoogleApi.Speech.V2.Model.CreatePhraseSetRequest)
  field(:"createRecognizerRequest", as: GoogleApi.Speech.V2.Model.CreateRecognizerRequest)
  field(:"createTime", as: DateTime)
  field(:"deleteCustomClassRequest", as: GoogleApi.Speech.V2.Model.DeleteCustomClassRequest)
  field(:"deletePhraseSetRequest", as: GoogleApi.Speech.V2.Model.DeletePhraseSetRequest)
  field(:"deleteRecognizerRequest", as: GoogleApi.Speech.V2.Model.DeleteRecognizerRequest)
  field(:"kmsKeyName")
  field(:"kmsKeyVersionName")
  field(:"method")
  field(:"progressPercent")
  field(:"resource")
  field(:"undeleteCustomClassRequest", as: GoogleApi.Speech.V2.Model.UndeleteCustomClassRequest)
  field(:"undeletePhraseSetRequest", as: GoogleApi.Speech.V2.Model.UndeletePhraseSetRequest)
  field(:"undeleteRecognizerRequest", as: GoogleApi.Speech.V2.Model.UndeleteRecognizerRequest)
  field(:"updateConfigRequest", as: GoogleApi.Speech.V2.Model.UpdateConfigRequest)
  field(:"updateCustomClassRequest", as: GoogleApi.Speech.V2.Model.UpdateCustomClassRequest)
  field(:"updatePhraseSetRequest", as: GoogleApi.Speech.V2.Model.UpdatePhraseSetRequest)
  field(:"updateRecognizerRequest", as: GoogleApi.Speech.V2.Model.UpdateRecognizerRequest)
  field(:"updateTime", as: DateTime)
end

defimpl Poison.Decoder, for: GoogleApi.Speech.V2.Model.OperationMetadata do
  def decode(value, options) do
    GoogleApi.Speech.V2.Model.OperationMetadata.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.Speech.V2.Model.OperationMetadata do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
