# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.YouTubeReporting.V1.Model.ListJobsResponse do
  @moduledoc """
  Response message for ReportingService.ListJobs.

  ## Attributes

  - jobs (List[Job]): The list of jobs. Defaults to: `null`.
  - nextPageToken (String): A token to retrieve next page of results. Pass this value in the ListJobsRequest.page_token field in the subsequent call to &#x60;ListJobs&#x60; method to retrieve the next page of results. Defaults to: `null`.
  """

  defstruct [
    :"jobs",
    :"nextPageToken"
  ]
end

defimpl Poison.Decoder, for: GoogleApi.YouTubeReporting.V1.Model.ListJobsResponse do
  import GoogleApi.YouTubeReporting.V1.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"jobs", :list, GoogleApi.YouTubeReporting.V1.Model.Job, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.YouTubeReporting.V1.Model.ListJobsResponse do
  def encode(value, options) do
    GoogleApi.YouTubeReporting.V1.Deserializer.serialize_non_nil(value, options)
  end
end

