# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the elixir code generator program.
# Do not edit the class manually.

defmodule GoogleApi.AdExchangeBuyer.V14.Model.PublisherProfileApiProto do
  @moduledoc """


  ## Attributes

  - audience (String.t): Publisher provided info on its audience. Defaults to `nil`.
  - buyerPitchStatement (String.t): A pitch statement for the buyer Defaults to `nil`.
  - directContact (String.t): Direct contact for the publisher profile. Defaults to `nil`.
  - exchange (String.t): Exchange where this publisher profile is from. E.g. AdX, Rubicon etc... Defaults to `nil`.
  - googlePlusLink (String.t): Link to publisher's Google+ page. Defaults to `nil`.
  - isParent (boolean()): True, if this is the parent profile, which represents all domains owned by the publisher. Defaults to `nil`.
  - isPublished (boolean()): True, if this profile is published. Deprecated for state. Defaults to `nil`.
  - kind (String.t): Identifies what kind of resource this is. Value: the fixed string "adexchangebuyer#publisherProfileApiProto". Defaults to `adexchangebuyer#publisherProfileApiProto`.
  - logoUrl (String.t): The url to the logo for the publisher. Defaults to `nil`.
  - mediaKitLink (String.t): The url for additional marketing and sales materials. Defaults to `nil`.
  - name (String.t):  Defaults to `nil`.
  - overview (String.t): Publisher provided overview. Defaults to `nil`.
  - profileId (integer()): The pair of (seller.account_id, profile_id) uniquely identifies a publisher profile for a given publisher. Defaults to `nil`.
  - programmaticContact (String.t): Programmatic contact for the publisher profile. Defaults to `nil`.
  - publisherDomains (list(String.t)): The list of domains represented in this publisher profile. Empty if this is a parent profile. Defaults to `nil`.
  - publisherProfileId (String.t): Unique Id for publisher profile. Defaults to `nil`.
  - publisherProvidedForecast (GoogleApi.AdExchangeBuyer.V14.Model.PublisherProvidedForecast.t): Publisher provided forecasting information. Defaults to `nil`.
  - rateCardInfoLink (String.t): Link to publisher rate card Defaults to `nil`.
  - samplePageLink (String.t): Link for a sample content page. Defaults to `nil`.
  - seller (GoogleApi.AdExchangeBuyer.V14.Model.Seller.t): Seller of the publisher profile. Defaults to `nil`.
  - state (String.t): State of the publisher profile. Defaults to `nil`.
  - topHeadlines (list(String.t)): Publisher provided key metrics and rankings. Defaults to `nil`.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :audience => String.t(),
          :buyerPitchStatement => String.t(),
          :directContact => String.t(),
          :exchange => String.t(),
          :googlePlusLink => String.t(),
          :isParent => boolean(),
          :isPublished => boolean(),
          :kind => String.t(),
          :logoUrl => String.t(),
          :mediaKitLink => String.t(),
          :name => String.t(),
          :overview => String.t(),
          :profileId => integer(),
          :programmaticContact => String.t(),
          :publisherDomains => list(String.t()),
          :publisherProfileId => String.t(),
          :publisherProvidedForecast =>
            GoogleApi.AdExchangeBuyer.V14.Model.PublisherProvidedForecast.t(),
          :rateCardInfoLink => String.t(),
          :samplePageLink => String.t(),
          :seller => GoogleApi.AdExchangeBuyer.V14.Model.Seller.t(),
          :state => String.t(),
          :topHeadlines => list(String.t())
        }

  field(:audience)
  field(:buyerPitchStatement)
  field(:directContact)
  field(:exchange)
  field(:googlePlusLink)
  field(:isParent)
  field(:isPublished)
  field(:kind)
  field(:logoUrl)
  field(:mediaKitLink)
  field(:name)
  field(:overview)
  field(:profileId)
  field(:programmaticContact)
  field(:publisherDomains, type: :list)
  field(:publisherProfileId)

  field(
    :publisherProvidedForecast,
    as: GoogleApi.AdExchangeBuyer.V14.Model.PublisherProvidedForecast
  )

  field(:rateCardInfoLink)
  field(:samplePageLink)
  field(:seller, as: GoogleApi.AdExchangeBuyer.V14.Model.Seller)
  field(:state)
  field(:topHeadlines, type: :list)
end

defimpl Poison.Decoder, for: GoogleApi.AdExchangeBuyer.V14.Model.PublisherProfileApiProto do
  def decode(value, options) do
    GoogleApi.AdExchangeBuyer.V14.Model.PublisherProfileApiProto.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.AdExchangeBuyer.V14.Model.PublisherProfileApiProto do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
