# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.CloudSearch.V1.Model.EnterpriseTopazSidekickMeetingNotesCardProto do
  @moduledoc """
  Information about the meeting notes created.

  ## Attributes

  *   `event` (*type:* `GoogleApi.CloudSearch.V1.Model.EnterpriseTopazSidekickAgendaEntry.t`, *default:* `nil`) - The event to request meeting notes creation.
  *   `fileId` (*type:* `String.t`, *default:* `nil`) - Google Drive ID (a.k.a. resource ID) of the file.
  *   `title` (*type:* `String.t`, *default:* `nil`) - Title we want to show for meeting notes in the answer card
  *   `url` (*type:* `String.t`, *default:* `nil`) - New URL.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :event => GoogleApi.CloudSearch.V1.Model.EnterpriseTopazSidekickAgendaEntry.t() | nil,
          :fileId => String.t() | nil,
          :title => String.t() | nil,
          :url => String.t() | nil
        }

  field(:event, as: GoogleApi.CloudSearch.V1.Model.EnterpriseTopazSidekickAgendaEntry)
  field(:fileId)
  field(:title)
  field(:url)
end

defimpl Poison.Decoder,
  for: GoogleApi.CloudSearch.V1.Model.EnterpriseTopazSidekickMeetingNotesCardProto do
  def decode(value, options) do
    GoogleApi.CloudSearch.V1.Model.EnterpriseTopazSidekickMeetingNotesCardProto.decode(
      value,
      options
    )
  end
end

defimpl Poison.Encoder,
  for: GoogleApi.CloudSearch.V1.Model.EnterpriseTopazSidekickMeetingNotesCardProto do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
