# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.MigrationCenter.V1.Model.AssetPerformanceData do
  @moduledoc """
  Performance data for an asset.

  ## Attributes

  *   `dailyResourceUsageAggregations` (*type:* `list(GoogleApi.MigrationCenter.V1.Model.DailyResourceUsageAggregation.t)`, *default:* `nil`) - Daily resource usage aggregations. Contains all of the data available for an asset, up to the last 420 days. Aggregations are sorted from oldest to most recent.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :dailyResourceUsageAggregations =>
            list(GoogleApi.MigrationCenter.V1.Model.DailyResourceUsageAggregation.t()) | nil
        }

  field(:dailyResourceUsageAggregations,
    as: GoogleApi.MigrationCenter.V1.Model.DailyResourceUsageAggregation,
    type: :list
  )
end

defimpl Poison.Decoder, for: GoogleApi.MigrationCenter.V1.Model.AssetPerformanceData do
  def decode(value, options) do
    GoogleApi.MigrationCenter.V1.Model.AssetPerformanceData.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.MigrationCenter.V1.Model.AssetPerformanceData do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
