# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.BigQuery.V2.Model.JobStatistics do
  @moduledoc """


  ## Attributes

  *   `completionRatio` (*type:* `float()`, *default:* `nil`) - [TrustedTester] [Output-only] Job progress (0.0 -> 1.0) for LOAD and EXTRACT jobs.
  *   `creationTime` (*type:* `String.t`, *default:* `nil`) - [Output-only] Creation time of this job, in milliseconds since the epoch. This field will be present on all jobs.
  *   `endTime` (*type:* `String.t`, *default:* `nil`) - [Output-only] End time of this job, in milliseconds since the epoch. This field will be present whenever a job is in the DONE state.
  *   `extract` (*type:* `GoogleApi.BigQuery.V2.Model.JobStatistics4.t`, *default:* `nil`) - [Output-only] Statistics for an extract job.
  *   `load` (*type:* `GoogleApi.BigQuery.V2.Model.JobStatistics3.t`, *default:* `nil`) - [Output-only] Statistics for a load job.
  *   `numChildJobs` (*type:* `String.t`, *default:* `nil`) - [Output-only] Number of child jobs executed.
  *   `parentJobId` (*type:* `String.t`, *default:* `nil`) - [Output-only] If this is a child job, the id of the parent.
  *   `query` (*type:* `GoogleApi.BigQuery.V2.Model.JobStatistics2.t`, *default:* `nil`) - [Output-only] Statistics for a query job.
  *   `quotaDeferments` (*type:* `list(String.t)`, *default:* `nil`) - [Output-only] Quotas which delayed this job's start time.
  *   `reservationUsage` (*type:* `list(GoogleApi.BigQuery.V2.Model.JobStatisticsReservationUsage.t)`, *default:* `nil`) - [Output-only] Job resource usage breakdown by reservation.
  *   `reservation_id` (*type:* `String.t`, *default:* `nil`) - [Output-only] Name of the primary reservation assigned to this job. Note that this could be different than reservations reported in the reservation usage field if parent reservations were used to execute this job.
  *   `startTime` (*type:* `String.t`, *default:* `nil`) - [Output-only] Start time of this job, in milliseconds since the epoch. This field will be present when the job transitions from the PENDING state to either RUNNING or DONE.
  *   `totalBytesProcessed` (*type:* `String.t`, *default:* `nil`) - [Output-only] [Deprecated] Use the bytes processed in the query statistics instead.
  *   `totalSlotMs` (*type:* `String.t`, *default:* `nil`) - [Output-only] Slot-milliseconds for the job.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :completionRatio => float(),
          :creationTime => String.t(),
          :endTime => String.t(),
          :extract => GoogleApi.BigQuery.V2.Model.JobStatistics4.t(),
          :load => GoogleApi.BigQuery.V2.Model.JobStatistics3.t(),
          :numChildJobs => String.t(),
          :parentJobId => String.t(),
          :query => GoogleApi.BigQuery.V2.Model.JobStatistics2.t(),
          :quotaDeferments => list(String.t()),
          :reservationUsage =>
            list(GoogleApi.BigQuery.V2.Model.JobStatisticsReservationUsage.t()),
          :reservation_id => String.t(),
          :startTime => String.t(),
          :totalBytesProcessed => String.t(),
          :totalSlotMs => String.t()
        }

  field(:completionRatio)
  field(:creationTime)
  field(:endTime)
  field(:extract, as: GoogleApi.BigQuery.V2.Model.JobStatistics4)
  field(:load, as: GoogleApi.BigQuery.V2.Model.JobStatistics3)
  field(:numChildJobs)
  field(:parentJobId)
  field(:query, as: GoogleApi.BigQuery.V2.Model.JobStatistics2)
  field(:quotaDeferments, type: :list)

  field(
    :reservationUsage,
    as: GoogleApi.BigQuery.V2.Model.JobStatisticsReservationUsage,
    type: :list
  )

  field(:reservation_id)
  field(:startTime)
  field(:totalBytesProcessed)
  field(:totalSlotMs)
end

defimpl Poison.Decoder, for: GoogleApi.BigQuery.V2.Model.JobStatistics do
  def decode(value, options) do
    GoogleApi.BigQuery.V2.Model.JobStatistics.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.BigQuery.V2.Model.JobStatistics do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
