# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.Directory.Directory_v1.Model.Group do
  @moduledoc """
  JSON template for Group resource in Directory API.

  ## Attributes
  
  *   `adminCreated` (*type:* `boolean()`, *default:* `nil`) - Is the group created by admin (Read-only) *
  *   `aliases` (*type:* `list(String.t)`, *default:* `nil`) - List of aliases (Read-only)
  *   `description` (*type:* `String.t`, *default:* `nil`) - Description of the group
  *   `directMembersCount` (*type:* `String.t`, *default:* `nil`) - Group direct members count
  *   `email` (*type:* `String.t`, *default:* `nil`) - Email of Group
  *   `etag` (*type:* `String.t`, *default:* `nil`) - ETag of the resource.
  *   `id` (*type:* `String.t`, *default:* `nil`) - Unique identifier of Group (Read-only)
  *   `kind` (*type:* `String.t`, *default:* `admin#directory#group`) - Kind of resource this is.
  *   `name` (*type:* `String.t`, *default:* `nil`) - Group name
  *   `nonEditableAliases` (*type:* `list(String.t)`, *default:* `nil`) - List of non editable aliases (Read-only)
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
    
      :"adminCreated" => boolean(),
    
      :"aliases" => list(String.t),
    
      :"description" => String.t,
    
      :"directMembersCount" => String.t,
    
      :"email" => String.t,
    
      :"etag" => String.t,
    
      :"id" => String.t,
    
      :"kind" => String.t,
    
      :"name" => String.t,
    
      :"nonEditableAliases" => list(String.t),
    
  }
  
  field(:"adminCreated")
  field(:"aliases", type: :list)
  field(:"description")
  field(:"directMembersCount")
  field(:"email")
  field(:"etag")
  field(:"id")
  field(:"kind")
  field(:"name")
  field(:"nonEditableAliases", type: :list)
end

defimpl Poison.Decoder, for: GoogleApi.Directory.Directory_v1.Model.Group do
  def decode(value, options) do
    GoogleApi.Directory.Directory_v1.Model.Group.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.Directory.Directory_v1.Model.Group do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
