# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.Container.V1.Model.GatewayAPIConfig do
  @moduledoc """
  GatewayAPIConfig contains the desired config of Gateway API on this cluster.

  ## Attributes

  *   `channel` (*type:* `String.t`, *default:* `nil`) - The Gateway API release channel to use for Gateway API.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :channel => String.t() | nil
        }

  field(:channel)
end

defimpl Poison.Decoder, for: GoogleApi.Container.V1.Model.GatewayAPIConfig do
  def decode(value, options) do
    GoogleApi.Container.V1.Model.GatewayAPIConfig.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.Container.V1.Model.GatewayAPIConfig do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
