# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.Container.V1.Model.NodeKubeletConfig do
  @moduledoc """
  Node kubelet configs.

  ## Attributes

  *   `cpuCfsQuota` (*type:* `boolean()`, *default:* `nil`) - Enable CPU CFS quota enforcement for containers that specify CPU limits. This option is enabled by default which makes kubelet use CFS quota (https://www.kernel.org/doc/Documentation/scheduler/sched-bwc.txt) to enforce container CPU limits. Otherwise, CPU limits will not be enforced at all. Disable this option to mitigate CPU throttling problems while still having your pods to be in Guaranteed QoS class by specifying the CPU limits. The default value is 'true' if unspecified.
  *   `cpuCfsQuotaPeriod` (*type:* `String.t`, *default:* `nil`) - Set the CPU CFS quota period value 'cpu.cfs_period_us'. The string must be a sequence of decimal numbers, each with optional fraction and a unit suffix, such as "300ms". Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h". The value must be a positive duration.
  *   `cpuManagerPolicy` (*type:* `String.t`, *default:* `nil`) - Control the CPU management policy on the node. See https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/ The following values are allowed. * "none": the default, which represents the existing scheduling behavior. * "static": allows pods with certain resource characteristics to be granted increased CPU affinity and exclusivity on the node. The default value is 'none' if unspecified.
  *   `insecureKubeletReadonlyPortEnabled` (*type:* `boolean()`, *default:* `nil`) - Enable or disable Kubelet read only port.
  *   `podPidsLimit` (*type:* `String.t`, *default:* `nil`) - Set the Pod PID limits. See https://kubernetes.io/docs/concepts/policy/pid-limiting/#pod-pid-limits Controls the maximum number of processes allowed to run in a pod. The value must be greater than or equal to 1024 and less than 4194304.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :cpuCfsQuota => boolean() | nil,
          :cpuCfsQuotaPeriod => String.t() | nil,
          :cpuManagerPolicy => String.t() | nil,
          :insecureKubeletReadonlyPortEnabled => boolean() | nil,
          :podPidsLimit => String.t() | nil
        }

  field(:cpuCfsQuota)
  field(:cpuCfsQuotaPeriod)
  field(:cpuManagerPolicy)
  field(:insecureKubeletReadonlyPortEnabled)
  field(:podPidsLimit)
end

defimpl Poison.Decoder, for: GoogleApi.Container.V1.Model.NodeKubeletConfig do
  def decode(value, options) do
    GoogleApi.Container.V1.Model.NodeKubeletConfig.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.Container.V1.Model.NodeKubeletConfig do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
