# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.Dataflow.V1b3.Model.ParameterMetadata do
  @moduledoc """
  Metadata for a specific parameter.

  ## Attributes

  - helpText (String.t): Required. The help text to display for the parameter. Defaults to: `null`.
  - isOptional (boolean()): Optional. Whether the parameter is optional. Defaults to false. Defaults to: `null`.
  - label (String.t): Required. The label to display for the parameter. Defaults to: `null`.
  - name (String.t): Required. The name of the parameter. Defaults to: `null`.
  - regexes ([String.t]): Optional. Regexes that the parameter must match. Defaults to: `null`.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :helpText => any(),
          :isOptional => any(),
          :label => any(),
          :name => any(),
          :regexes => list(any())
        }

  field(:helpText)
  field(:isOptional)
  field(:label)
  field(:name)
  field(:regexes, type: :list)
end

defimpl Poison.Decoder, for: GoogleApi.Dataflow.V1b3.Model.ParameterMetadata do
  def decode(value, options) do
    GoogleApi.Dataflow.V1b3.Model.ParameterMetadata.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.Dataflow.V1b3.Model.ParameterMetadata do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
