# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.DFAReporting.V28.Model.CreativeAsset do
  @moduledoc """
  Creative Asset.

  ## Attributes

  - actionScript3 (boolean()): Whether ActionScript3 is enabled for the flash asset. This is a read-only field. Applicable to the following creative type: FLASH_INPAGE. Applicable to DISPLAY when the primary asset type is not HTML_IMAGE. Defaults to: `null`.
  - active (boolean()): Whether the video asset is active. This is a read-only field for VPAID_NON_LINEAR_VIDEO assets. Applicable to the following creative types: INSTREAM_VIDEO and all VPAID. Defaults to: `null`.
  - alignment (String.t): Possible alignments for an asset. This is a read-only field. Applicable to the following creative types: RICH_MEDIA_DISPLAY_MULTI_FLOATING_INTERSTITIAL. Defaults to: `null`.
    - Enum - one of [ALIGNMENT_BOTTOM, ALIGNMENT_LEFT, ALIGNMENT_RIGHT, ALIGNMENT_TOP]
  - artworkType (String.t): Artwork type of rich media creative. This is a read-only field. Applicable to the following creative types: all RICH_MEDIA. Defaults to: `null`.
    - Enum - one of [ARTWORK_TYPE_FLASH, ARTWORK_TYPE_HTML5, ARTWORK_TYPE_IMAGE, ARTWORK_TYPE_MIXED]
  - assetIdentifier (CreativeAssetId): Identifier of this asset. This is the same identifier returned during creative asset insert operation. This is a required field. Applicable to all but the following creative types: all REDIRECT and TRACKING_TEXT. Defaults to: `null`.
  - backupImageExit (CreativeCustomEvent): Exit event configured for the backup image. Applicable to the following creative types: all RICH_MEDIA. Defaults to: `null`.
  - bitRate (integer()): Detected bit-rate for video asset. This is a read-only field. Applicable to the following creative types: INSTREAM_VIDEO and all VPAID. Defaults to: `null`.
  - childAssetType (String.t): Rich media child asset type. This is a read-only field. Applicable to the following creative types: all VPAID. Defaults to: `null`.
    - Enum - one of [CHILD_ASSET_TYPE_DATA, CHILD_ASSET_TYPE_FLASH, CHILD_ASSET_TYPE_IMAGE, CHILD_ASSET_TYPE_VIDEO]
  - collapsedSize (Size): Size of an asset when collapsed. This is a read-only field. Applicable to the following creative types: all RICH_MEDIA and all VPAID. Additionally, applicable to assets whose displayType is ASSET_DISPLAY_TYPE_EXPANDING or ASSET_DISPLAY_TYPE_PEEL_DOWN. Defaults to: `null`.
  - companionCreativeIds ([String.t]): List of companion creatives assigned to an in-stream video creative asset. Acceptable values include IDs of existing flash and image creatives. Applicable to INSTREAM_VIDEO creative type with dynamicAssetSelection set to true. Defaults to: `null`.
  - customStartTimeValue (integer()): Custom start time in seconds for making the asset visible. Applicable to the following creative types: all RICH_MEDIA. Value must be greater than or equal to 0. Defaults to: `null`.
  - detectedFeatures ([String.t]): List of feature dependencies for the creative asset that are detected by Campaign Manager. Feature dependencies are features that a browser must be able to support in order to render your HTML5 creative correctly. This is a read-only, auto-generated field. Applicable to the following creative types: HTML5_BANNER. Applicable to DISPLAY when the primary asset type is not HTML_IMAGE. Defaults to: `null`.
    - Enum - one of 
  - displayType (String.t): Type of rich media asset. This is a read-only field. Applicable to the following creative types: all RICH_MEDIA. Defaults to: `null`.
    - Enum - one of [ASSET_DISPLAY_TYPE_BACKDROP, ASSET_DISPLAY_TYPE_EXPANDING, ASSET_DISPLAY_TYPE_FLASH_IN_FLASH, ASSET_DISPLAY_TYPE_FLASH_IN_FLASH_EXPANDING, ASSET_DISPLAY_TYPE_FLOATING, ASSET_DISPLAY_TYPE_INPAGE, ASSET_DISPLAY_TYPE_OVERLAY, ASSET_DISPLAY_TYPE_PEEL_DOWN, ASSET_DISPLAY_TYPE_VPAID_LINEAR, ASSET_DISPLAY_TYPE_VPAID_NON_LINEAR]
  - duration (integer()): Duration in seconds for which an asset will be displayed. Applicable to the following creative types: INSTREAM_VIDEO and VPAID_LINEAR_VIDEO. Value must be greater than or equal to 1. Defaults to: `null`.
  - durationType (String.t): Duration type for which an asset will be displayed. Applicable to the following creative types: all RICH_MEDIA. Defaults to: `null`.
    - Enum - one of [ASSET_DURATION_TYPE_AUTO, ASSET_DURATION_TYPE_CUSTOM, ASSET_DURATION_TYPE_NONE]
  - expandedDimension (Size): Detected expanded dimension for video asset. This is a read-only field. Applicable to the following creative types: INSTREAM_VIDEO and all VPAID. Defaults to: `null`.
  - fileSize (String.t): File size associated with this creative asset. This is a read-only field. Applicable to all but the following creative types: all REDIRECT and TRACKING_TEXT. Defaults to: `null`.
  - flashVersion (integer()): Flash version of the asset. This is a read-only field. Applicable to the following creative types: FLASH_INPAGE, all RICH_MEDIA, and all VPAID. Applicable to DISPLAY when the primary asset type is not HTML_IMAGE. Defaults to: `null`.
  - hideFlashObjects (boolean()): Whether to hide Flash objects flag for an asset. Applicable to the following creative types: all RICH_MEDIA. Defaults to: `null`.
  - hideSelectionBoxes (boolean()): Whether to hide selection boxes flag for an asset. Applicable to the following creative types: all RICH_MEDIA. Defaults to: `null`.
  - horizontallyLocked (boolean()): Whether the asset is horizontally locked. This is a read-only field. Applicable to the following creative types: all RICH_MEDIA. Defaults to: `null`.
  - id (String.t): Numeric ID of this creative asset. This is a required field and should not be modified. Applicable to all but the following creative types: all REDIRECT and TRACKING_TEXT. Defaults to: `null`.
  - idDimensionValue (DimensionValue): Dimension value for the ID of the asset. This is a read-only, auto-generated field. Defaults to: `null`.
  - mimeType (String.t): Detected MIME type for video asset. This is a read-only field. Applicable to the following creative types: INSTREAM_VIDEO and all VPAID. Defaults to: `null`.
  - offset (OffsetPosition): Offset position for an asset in collapsed mode. This is a read-only field. Applicable to the following creative types: all RICH_MEDIA and all VPAID. Additionally, only applicable to assets whose displayType is ASSET_DISPLAY_TYPE_EXPANDING or ASSET_DISPLAY_TYPE_PEEL_DOWN. Defaults to: `null`.
  - originalBackup (boolean()): Whether the backup asset is original or changed by the user in Campaign Manager. Applicable to the following creative types: all RICH_MEDIA. Defaults to: `null`.
  - position (OffsetPosition): Offset position for an asset. Applicable to the following creative types: all RICH_MEDIA. Defaults to: `null`.
  - positionLeftUnit (String.t): Offset left unit for an asset. This is a read-only field. Applicable to the following creative types: all RICH_MEDIA. Defaults to: `null`.
    - Enum - one of [OFFSET_UNIT_PERCENT, OFFSET_UNIT_PIXEL, OFFSET_UNIT_PIXEL_FROM_CENTER]
  - positionTopUnit (String.t): Offset top unit for an asset. This is a read-only field if the asset displayType is ASSET_DISPLAY_TYPE_OVERLAY. Applicable to the following creative types: all RICH_MEDIA. Defaults to: `null`.
    - Enum - one of [OFFSET_UNIT_PERCENT, OFFSET_UNIT_PIXEL, OFFSET_UNIT_PIXEL_FROM_CENTER]
  - progressiveServingUrl (String.t): Progressive URL for video asset. This is a read-only field. Applicable to the following creative types: INSTREAM_VIDEO and all VPAID. Defaults to: `null`.
  - pushdown (boolean()): Whether the asset pushes down other content. Applicable to the following creative types: all RICH_MEDIA. Additionally, only applicable when the asset offsets are 0, the collapsedSize.width matches size.width, and the collapsedSize.height is less than size.height. Defaults to: `null`.
  - pushdownDuration (float()): Pushdown duration in seconds for an asset. Applicable to the following creative types: all RICH_MEDIA.Additionally, only applicable when the asset pushdown field is true, the offsets are 0, the collapsedSize.width matches size.width, and the collapsedSize.height is less than size.height. Acceptable values are 0 to 9.99, inclusive. Defaults to: `null`.
  - role (String.t): Role of the asset in relation to creative. Applicable to all but the following creative types: all REDIRECT and TRACKING_TEXT. This is a required field. PRIMARY applies to DISPLAY, FLASH_INPAGE, HTML5_BANNER, IMAGE, DISPLAY_IMAGE_GALLERY, all RICH_MEDIA (which may contain multiple primary assets), and all VPAID creatives. BACKUP_IMAGE applies to FLASH_INPAGE, HTML5_BANNER, all RICH_MEDIA, and all VPAID creatives. Applicable to DISPLAY when the primary asset type is not HTML_IMAGE. ADDITIONAL_IMAGE and ADDITIONAL_FLASH apply to FLASH_INPAGE creatives. OTHER refers to assets from sources other than Campaign Manager, such as Studio uploaded assets, applicable to all RICH_MEDIA and all VPAID creatives. PARENT_VIDEO refers to videos uploaded by the user in Campaign Manager and is applicable to INSTREAM_VIDEO and VPAID_LINEAR_VIDEO creatives. TRANSCODED_VIDEO refers to videos transcoded by Campaign Manager from PARENT_VIDEO assets and is applicable to INSTREAM_VIDEO and VPAID_LINEAR_VIDEO creatives. ALTERNATE_VIDEO refers to the Campaign Manager representation of child asset videos from Studio, and is applicable to VPAID_LINEAR_VIDEO creatives. These cannot be added or removed within Campaign Manager. For VPAID_LINEAR_VIDEO creatives, PARENT_VIDEO, TRANSCODED_VIDEO and ALTERNATE_VIDEO assets that are marked active serve as backup in case the VPAID creative cannot be served. Only PARENT_VIDEO assets can be added or removed for an INSTREAM_VIDEO or VPAID_LINEAR_VIDEO creative. Defaults to: `null`.
    - Enum - one of [ADDITIONAL_FLASH, ADDITIONAL_IMAGE, ALTERNATE_VIDEO, BACKUP_IMAGE, OTHER, PARENT_VIDEO, PRIMARY, TRANSCODED_VIDEO]
  - size (Size): Size associated with this creative asset. This is a required field when applicable; however for IMAGE and FLASH_INPAGE, creatives if left blank, this field will be automatically set using the actual size of the associated image asset. Applicable to the following creative types: DISPLAY_IMAGE_GALLERY, FLASH_INPAGE, HTML5_BANNER, IMAGE, and all RICH_MEDIA. Applicable to DISPLAY when the primary asset type is not HTML_IMAGE. Defaults to: `null`.
  - sslCompliant (boolean()): Whether the asset is SSL-compliant. This is a read-only field. Applicable to all but the following creative types: all REDIRECT and TRACKING_TEXT. Defaults to: `null`.
  - startTimeType (String.t): Initial wait time type before making the asset visible. Applicable to the following creative types: all RICH_MEDIA. Defaults to: `null`.
    - Enum - one of [ASSET_START_TIME_TYPE_CUSTOM, ASSET_START_TIME_TYPE_NONE]
  - streamingServingUrl (String.t): Streaming URL for video asset. This is a read-only field. Applicable to the following creative types: INSTREAM_VIDEO and all VPAID. Defaults to: `null`.
  - transparency (boolean()): Whether the asset is transparent. Applicable to the following creative types: all RICH_MEDIA. Additionally, only applicable to HTML5 assets. Defaults to: `null`.
  - verticallyLocked (boolean()): Whether the asset is vertically locked. This is a read-only field. Applicable to the following creative types: all RICH_MEDIA. Defaults to: `null`.
  - videoDuration (float()): Detected video duration for video asset. This is a read-only field. Applicable to the following creative types: INSTREAM_VIDEO and all VPAID. Defaults to: `null`.
  - windowMode (String.t): Window mode options for flash assets. Applicable to the following creative types: FLASH_INPAGE, RICH_MEDIA_DISPLAY_EXPANDING, RICH_MEDIA_IM_EXPAND, RICH_MEDIA_DISPLAY_BANNER, and RICH_MEDIA_INPAGE_FLOATING. Defaults to: `null`.
    - Enum - one of [OPAQUE, TRANSPARENT, WINDOW]
  - zIndex (integer()): zIndex value of an asset. Applicable to the following creative types: all RICH_MEDIA.Additionally, only applicable to assets whose displayType is NOT one of the following types: ASSET_DISPLAY_TYPE_INPAGE or ASSET_DISPLAY_TYPE_OVERLAY. Acceptable values are -999999999 to 999999999, inclusive. Defaults to: `null`.
  - zipFilename (String.t): File name of zip file. This is a read-only field. Applicable to the following creative types: HTML5_BANNER. Defaults to: `null`.
  - zipFilesize (String.t): Size of zip file. This is a read-only field. Applicable to the following creative types: HTML5_BANNER. Defaults to: `null`.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :actionScript3 => any(),
          :active => any(),
          :alignment => any(),
          :artworkType => any(),
          :assetIdentifier => GoogleApi.DFAReporting.V28.Model.CreativeAssetId.t(),
          :backupImageExit => GoogleApi.DFAReporting.V28.Model.CreativeCustomEvent.t(),
          :bitRate => any(),
          :childAssetType => any(),
          :collapsedSize => GoogleApi.DFAReporting.V28.Model.Size.t(),
          :companionCreativeIds => list(any()),
          :customStartTimeValue => any(),
          :detectedFeatures => list(any()),
          :displayType => any(),
          :duration => any(),
          :durationType => any(),
          :expandedDimension => GoogleApi.DFAReporting.V28.Model.Size.t(),
          :fileSize => any(),
          :flashVersion => any(),
          :hideFlashObjects => any(),
          :hideSelectionBoxes => any(),
          :horizontallyLocked => any(),
          :id => any(),
          :idDimensionValue => GoogleApi.DFAReporting.V28.Model.DimensionValue.t(),
          :mimeType => any(),
          :offset => GoogleApi.DFAReporting.V28.Model.OffsetPosition.t(),
          :originalBackup => any(),
          :position => GoogleApi.DFAReporting.V28.Model.OffsetPosition.t(),
          :positionLeftUnit => any(),
          :positionTopUnit => any(),
          :progressiveServingUrl => any(),
          :pushdown => any(),
          :pushdownDuration => any(),
          :role => any(),
          :size => GoogleApi.DFAReporting.V28.Model.Size.t(),
          :sslCompliant => any(),
          :startTimeType => any(),
          :streamingServingUrl => any(),
          :transparency => any(),
          :verticallyLocked => any(),
          :videoDuration => any(),
          :windowMode => any(),
          :zIndex => any(),
          :zipFilename => any(),
          :zipFilesize => any()
        }

  field(:actionScript3)
  field(:active)
  field(:alignment)
  field(:artworkType)
  field(:assetIdentifier, as: GoogleApi.DFAReporting.V28.Model.CreativeAssetId)
  field(:backupImageExit, as: GoogleApi.DFAReporting.V28.Model.CreativeCustomEvent)
  field(:bitRate)
  field(:childAssetType)
  field(:collapsedSize, as: GoogleApi.DFAReporting.V28.Model.Size)
  field(:companionCreativeIds, type: :list)
  field(:customStartTimeValue)
  field(:detectedFeatures, type: :list)
  field(:displayType)
  field(:duration)
  field(:durationType)
  field(:expandedDimension, as: GoogleApi.DFAReporting.V28.Model.Size)
  field(:fileSize)
  field(:flashVersion)
  field(:hideFlashObjects)
  field(:hideSelectionBoxes)
  field(:horizontallyLocked)
  field(:id)
  field(:idDimensionValue, as: GoogleApi.DFAReporting.V28.Model.DimensionValue)
  field(:mimeType)
  field(:offset, as: GoogleApi.DFAReporting.V28.Model.OffsetPosition)
  field(:originalBackup)
  field(:position, as: GoogleApi.DFAReporting.V28.Model.OffsetPosition)
  field(:positionLeftUnit)
  field(:positionTopUnit)
  field(:progressiveServingUrl)
  field(:pushdown)
  field(:pushdownDuration)
  field(:role)
  field(:size, as: GoogleApi.DFAReporting.V28.Model.Size)
  field(:sslCompliant)
  field(:startTimeType)
  field(:streamingServingUrl)
  field(:transparency)
  field(:verticallyLocked)
  field(:videoDuration)
  field(:windowMode)
  field(:zIndex)
  field(:zipFilename)
  field(:zipFilesize)
end

defimpl Poison.Decoder, for: GoogleApi.DFAReporting.V28.Model.CreativeAsset do
  def decode(value, options) do
    GoogleApi.DFAReporting.V28.Model.CreativeAsset.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.DFAReporting.V28.Model.CreativeAsset do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
