# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.AndroidDeviceProvisioning.V1.Model.Company do
  @moduledoc """
  Company

  ## Attributes

  - adminEmails (List[String]): Admin email. Admins will be able to operate on the portal. This field is a WRITE-only field at creation time. Defaults to: `null`.
  - companyId (String): company id Defaults to: `null`.
  - companyName (String): company name Defaults to: `null`.
  - name (String): REST Resource name. Defaults to: `null`.
  - ownerEmails (List[String]): Owner email. Owner is able to operate on the portal, and modify admins and other owners. This field is a WRITE-only field at creation time. Defaults to: `null`.
  """

  defstruct [
    :"adminEmails",
    :"companyId",
    :"companyName",
    :"name",
    :"ownerEmails"
  ]
end

defimpl Poison.Decoder, for: GoogleApi.AndroidDeviceProvisioning.V1.Model.Company do
  def decode(value, _options) do
    value
  end
end

defimpl Poison.Encoder, for: GoogleApi.AndroidDeviceProvisioning.V1.Model.Company do
  def encode(value, options) do
    GoogleApi.AndroidDeviceProvisioning.V1.Deserializer.serialize_non_nil(value, options)
  end
end

