# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.BackupDR.V1.Model.AliasIpRange do
  @moduledoc """
  An alias IP range attached to an instance's network interface.

  ## Attributes

  *   `ipCidrRange` (*type:* `String.t`, *default:* `nil`) - Optional. The IP alias ranges to allocate for this interface.
  *   `subnetworkRangeName` (*type:* `String.t`, *default:* `nil`) - Optional. The name of a subnetwork secondary IP range from which to allocate an IP alias range. If not specified, the primary range of the subnetwork is used.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :ipCidrRange => String.t() | nil,
          :subnetworkRangeName => String.t() | nil
        }

  field(:ipCidrRange)
  field(:subnetworkRangeName)
end

defimpl Poison.Decoder, for: GoogleApi.BackupDR.V1.Model.AliasIpRange do
  def decode(value, options) do
    GoogleApi.BackupDR.V1.Model.AliasIpRange.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.BackupDR.V1.Model.AliasIpRange do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
