# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the elixir code generator program.
# Do not edit the class manually.

defmodule GoogleApi.Sheets.V4.Model.MatchedDeveloperMetadata do
  @moduledoc """
  A developer metadata entry and the data filters specified in the original
  request that matched it.

  ## Attributes

  - dataFilters (list(GoogleApi.Sheets.V4.Model.DataFilter.t)): All filters matching the returned developer metadata. Defaults to `nil`.
  - developerMetadata (GoogleApi.Sheets.V4.Model.DeveloperMetadata.t): The developer metadata matching the specified filters. Defaults to `nil`.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :dataFilters => list(GoogleApi.Sheets.V4.Model.DataFilter.t()),
          :developerMetadata => GoogleApi.Sheets.V4.Model.DeveloperMetadata.t()
        }

  field(:dataFilters, as: GoogleApi.Sheets.V4.Model.DataFilter, type: :list)
  field(:developerMetadata, as: GoogleApi.Sheets.V4.Model.DeveloperMetadata)
end

defimpl Poison.Decoder, for: GoogleApi.Sheets.V4.Model.MatchedDeveloperMetadata do
  def decode(value, options) do
    GoogleApi.Sheets.V4.Model.MatchedDeveloperMetadata.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.Sheets.V4.Model.MatchedDeveloperMetadata do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
