# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.AppEngine.V1.Model.ListRuntimesResponse do
  @moduledoc """
  Response message for Applications.ListRuntimes.

  ## Attributes

  *   `nextPageToken` (*type:* `String.t`, *default:* `nil`) - Continuation token for fetching the next page of results.
  *   `runtimes` (*type:* `list(GoogleApi.AppEngine.V1.Model.Runtime.t)`, *default:* `nil`) - The runtimes available to the requested application.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :nextPageToken => String.t() | nil,
          :runtimes => list(GoogleApi.AppEngine.V1.Model.Runtime.t()) | nil
        }

  field(:nextPageToken)
  field(:runtimes, as: GoogleApi.AppEngine.V1.Model.Runtime, type: :list)
end

defimpl Poison.Decoder, for: GoogleApi.AppEngine.V1.Model.ListRuntimesResponse do
  def decode(value, options) do
    GoogleApi.AppEngine.V1.Model.ListRuntimesResponse.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.AppEngine.V1.Model.ListRuntimesResponse do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
