# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.AndroidPublisher.V3.Model.UserInitiatedCancellation do
  @moduledoc """
  Information specific to cancellations initiated by users.

  ## Attributes

  *   `cancelSurveyResult` (*type:* `GoogleApi.AndroidPublisher.V3.Model.CancelSurveyResult.t`, *default:* `nil`) - Information provided by the user when they complete the subscription cancellation flow (cancellation reason survey).
  *   `cancelTime` (*type:* `DateTime.t`, *default:* `nil`) - The time at which the subscription was canceled by the user. The user might still have access to the subscription after this time. Use line_items.expiry_time to determine if a user still has access.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :cancelSurveyResult => GoogleApi.AndroidPublisher.V3.Model.CancelSurveyResult.t() | nil,
          :cancelTime => DateTime.t() | nil
        }

  field(:cancelSurveyResult, as: GoogleApi.AndroidPublisher.V3.Model.CancelSurveyResult)
  field(:cancelTime, as: DateTime)
end

defimpl Poison.Decoder, for: GoogleApi.AndroidPublisher.V3.Model.UserInitiatedCancellation do
  def decode(value, options) do
    GoogleApi.AndroidPublisher.V3.Model.UserInitiatedCancellation.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.AndroidPublisher.V3.Model.UserInitiatedCancellation do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
