# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.PageSpeedOnline.V5.Model.LhrEntity do
  @moduledoc """
  Message containing an Entity.

  ## Attributes

  *   `category` (*type:* `String.t`, *default:* `nil`) - Optional. An optional category name for the entity.
  *   `homepage` (*type:* `String.t`, *default:* `nil`) - Optional. An optional homepage URL of the entity.
  *   `isFirstParty` (*type:* `boolean()`, *default:* `nil`) - Optional. An optional flag indicating if the entity is the first party.
  *   `isUnrecognized` (*type:* `boolean()`, *default:* `nil`) - Optional. An optional flag indicating if the entity is not recognized.
  *   `name` (*type:* `String.t`, *default:* `nil`) - Required. Name of the entity.
  *   `origins` (*type:* `list(String.t)`, *default:* `nil`) - Required. A list of URL origin strings that belong to this entity.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :category => String.t() | nil,
          :homepage => String.t() | nil,
          :isFirstParty => boolean() | nil,
          :isUnrecognized => boolean() | nil,
          :name => String.t() | nil,
          :origins => list(String.t()) | nil
        }

  field(:category)
  field(:homepage)
  field(:isFirstParty)
  field(:isUnrecognized)
  field(:name)
  field(:origins, type: :list)
end

defimpl Poison.Decoder, for: GoogleApi.PageSpeedOnline.V5.Model.LhrEntity do
  def decode(value, options) do
    GoogleApi.PageSpeedOnline.V5.Model.LhrEntity.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.PageSpeedOnline.V5.Model.LhrEntity do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
