# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.GKEOnPrem.V1.Model.VmwareNodePoolAutoscalingConfig do
  @moduledoc """
  NodePoolAutoscaling config for the NodePool to allow for the kubernetes to scale NodePool.

  ## Attributes

  *   `maxReplicas` (*type:* `integer()`, *default:* `nil`) - Maximum number of replicas in the NodePool.
  *   `minReplicas` (*type:* `integer()`, *default:* `nil`) - Minimum number of replicas in the NodePool.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :maxReplicas => integer() | nil,
          :minReplicas => integer() | nil
        }

  field(:maxReplicas)
  field(:minReplicas)
end

defimpl Poison.Decoder, for: GoogleApi.GKEOnPrem.V1.Model.VmwareNodePoolAutoscalingConfig do
  def decode(value, options) do
    GoogleApi.GKEOnPrem.V1.Model.VmwareNodePoolAutoscalingConfig.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.GKEOnPrem.V1.Model.VmwareNodePoolAutoscalingConfig do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
