# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.Docs.V1.Model.SectionStyle do
  @moduledoc """
  The styling that applies to a section.

  ## Attributes

  *   `columnProperties` (*type:* `list(GoogleApi.Docs.V1.Model.SectionColumnProperties.t)`, *default:* `nil`) - The section's columns properties.

      If empty, the section contains one column with the default properties in
      the Docs editor.
      A section can be updated to have no more than three columns.

      When updating this property, setting a concrete value is required.
      Unsetting this property will result in a 400 bad request error.
  *   `columnSeparatorStyle` (*type:* `String.t`, *default:* `nil`) - The style of column separators.

      This style can be set even when there is one column in the section.

      When updating this property, setting a concrete value is required.
      Unsetting this property results in a 400 bad request error.
  *   `contentDirection` (*type:* `String.t`, *default:* `nil`) - The content direction of this section. If unset, the value defaults to
      LEFT_TO_RIGHT.

      When updating this property, setting a concrete value is required.
      Unsetting this property results in a 400 bad request error.
  *   `defaultFooterId` (*type:* `String.t`, *default:* `nil`) - The ID of the default footer. If unset, the value inherits from the
      previous SectionBreak's SectionStyle.
      If the value is unset in the first SectionBreak, it inherits from
      DocumentStyle's default_footer_id.

      This property is read-only.
  *   `defaultHeaderId` (*type:* `String.t`, *default:* `nil`) - The ID of the default header. If unset, the value inherits from the
      previous SectionBreak's SectionStyle.
      If the value is unset in the first SectionBreak, it inherits from
      DocumentStyle's default_header_id.

      This property is read-only.
  *   `evenPageFooterId` (*type:* `String.t`, *default:* `nil`) - The ID of the footer used only for even pages. If the value of
      DocumentStyle's use_even_page_header_footer is true,
      this value is used for the footers on even pages in the section. If it
      is false, the footers on even pages uses the default_footer_id. If unset, the value
      inherits from the previous SectionBreak's SectionStyle. If the value is unset in
      the first SectionBreak, it inherits from DocumentStyle's
      even_page_footer_id.

      This property is read-only.
  *   `evenPageHeaderId` (*type:* `String.t`, *default:* `nil`) - The ID of the header used only for even pages. If the value of
      DocumentStyle's use_even_page_header_footer is true,
      this value is used for the headers on even pages in the section. If it
      is false, the headers on even pages uses the default_header_id. If unset, the value
      inherits from the previous SectionBreak's SectionStyle. If the value is unset in
      the first SectionBreak, it inherits from DocumentStyle's
      even_page_header_id.

      This property is read-only.
  *   `firstPageFooterId` (*type:* `String.t`, *default:* `nil`) - The ID of the footer used only for the first page of the section.
      If use_first_page_header_footer is true,
      this value is used for the footer on the first page of the section. If
      it is false, the footer on the first page of the section uses the
      default_footer_id.
      If unset, the value inherits from the previous SectionBreak's SectionStyle. If the value is unset in
      the first SectionBreak, it inherits from DocumentStyle's
      first_page_footer_id.

      This property is read-only.
  *   `firstPageHeaderId` (*type:* `String.t`, *default:* `nil`) - The ID of the header used only for the first page of the section.
      If use_first_page_header_footer is true,
      this value is used for the header on the first page of the section. If
      it is false, the header on the first page of the section uses the
      default_header_id.
      If unset, the value inherits from the previous SectionBreak's SectionStyle. If the value is unset in
      the first SectionBreak, it inherits from DocumentStyle's
      first_page_header_id.

      This property is read-only.
  *   `marginBottom` (*type:* `GoogleApi.Docs.V1.Model.Dimension.t`, *default:* `nil`) - The bottom page margin of the section. If unset, uses margin_bottom from DocumentStyle.

      When updating this property, setting a concrete value is required.
      Unsetting this property results in a 400 bad request error.
  *   `marginFooter` (*type:* `GoogleApi.Docs.V1.Model.Dimension.t`, *default:* `nil`) - The footer margin of the section. If unset, uses margin_footer from DocumentStyle. If
      updated, use_custom_header_footer_margins is set
      to true on DocumentStyle. The value of use_custom_header_footer_margins on
      DocumentStyle indicates if a footer margin is being respected for this
      section

      When updating this property, setting a concrete value is required.
      Unsetting this property results in a 400 bad request error.
  *   `marginHeader` (*type:* `GoogleApi.Docs.V1.Model.Dimension.t`, *default:* `nil`) - The header margin of the section. If unset, uses margin_header from DocumentStyle. If
      updated, use_custom_header_footer_margins is set
      to true on DocumentStyle. The value of use_custom_header_footer_margins on
      DocumentStyle indicates if a header margin is being respected for this
      section.

      When updating this property, setting a concrete value is required.
      Unsetting this property results in a 400 bad request error.
  *   `marginLeft` (*type:* `GoogleApi.Docs.V1.Model.Dimension.t`, *default:* `nil`) - The left page margin of the section. If unset, uses margin_left from DocumentStyle.
      Updating left margin causes columns in this section to resize. Since
      the margin affects column width, it is applied before column properties.

      When updating this property, setting a concrete value is required.
      Unsetting this property results in a 400 bad request error.
  *   `marginRight` (*type:* `GoogleApi.Docs.V1.Model.Dimension.t`, *default:* `nil`) - The right page margin of the section. If unset, uses margin_right from DocumentStyle.
      Updating right margin causes columns in this section to resize. Since
      the margin affects column width, it is applied before column properties.

      When updating this property, setting a concrete value is required.
      Unsetting this property results in a 400 bad request error.
  *   `marginTop` (*type:* `GoogleApi.Docs.V1.Model.Dimension.t`, *default:* `nil`) - The top page margin of the section. If unset, uses margin_top from DocumentStyle.

      When updating this property, setting a concrete value is required.
      Unsetting this property results in a 400 bad request error.
  *   `pageNumberStart` (*type:* `integer()`, *default:* `nil`) - The page number from which to start counting the number of pages for this
      section. If unset, page numbering continues from the previous section.
      If the value is unset in the first
      SectionBreak, refer to DocumentStyle's
      page_number_start.

      When updating this property, setting a concrete value is required.
      Unsetting this property results in a 400 bad request error.
  *   `sectionType` (*type:* `String.t`, *default:* `nil`) - Output only. The type of section.
  *   `useFirstPageHeaderFooter` (*type:* `boolean()`, *default:* `nil`) - Indicates whether to use the first page header / footer IDs for the first
      page of the section. If unset, it inherits from DocumentStyle's
      use_first_page_header_footer for the
      first section. If the value is unset for subsequent sectors, it should be
      interpreted as false.

      When updating this property, setting a concrete value is required.
      Unsetting this property results in a 400 bad request error.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :columnProperties => list(GoogleApi.Docs.V1.Model.SectionColumnProperties.t()),
          :columnSeparatorStyle => String.t(),
          :contentDirection => String.t(),
          :defaultFooterId => String.t(),
          :defaultHeaderId => String.t(),
          :evenPageFooterId => String.t(),
          :evenPageHeaderId => String.t(),
          :firstPageFooterId => String.t(),
          :firstPageHeaderId => String.t(),
          :marginBottom => GoogleApi.Docs.V1.Model.Dimension.t(),
          :marginFooter => GoogleApi.Docs.V1.Model.Dimension.t(),
          :marginHeader => GoogleApi.Docs.V1.Model.Dimension.t(),
          :marginLeft => GoogleApi.Docs.V1.Model.Dimension.t(),
          :marginRight => GoogleApi.Docs.V1.Model.Dimension.t(),
          :marginTop => GoogleApi.Docs.V1.Model.Dimension.t(),
          :pageNumberStart => integer(),
          :sectionType => String.t(),
          :useFirstPageHeaderFooter => boolean()
        }

  field(:columnProperties, as: GoogleApi.Docs.V1.Model.SectionColumnProperties, type: :list)
  field(:columnSeparatorStyle)
  field(:contentDirection)
  field(:defaultFooterId)
  field(:defaultHeaderId)
  field(:evenPageFooterId)
  field(:evenPageHeaderId)
  field(:firstPageFooterId)
  field(:firstPageHeaderId)
  field(:marginBottom, as: GoogleApi.Docs.V1.Model.Dimension)
  field(:marginFooter, as: GoogleApi.Docs.V1.Model.Dimension)
  field(:marginHeader, as: GoogleApi.Docs.V1.Model.Dimension)
  field(:marginLeft, as: GoogleApi.Docs.V1.Model.Dimension)
  field(:marginRight, as: GoogleApi.Docs.V1.Model.Dimension)
  field(:marginTop, as: GoogleApi.Docs.V1.Model.Dimension)
  field(:pageNumberStart)
  field(:sectionType)
  field(:useFirstPageHeaderFooter)
end

defimpl Poison.Decoder, for: GoogleApi.Docs.V1.Model.SectionStyle do
  def decode(value, options) do
    GoogleApi.Docs.V1.Model.SectionStyle.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.Docs.V1.Model.SectionStyle do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
