# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.SourceRepo.V1.Model.Repo do
  @moduledoc """
  A repository (or repo) is a Git repository storing versioned source content.

  ## Attributes

  - mirrorConfig (MirrorConfig): How this repository mirrors a repository managed by another service. Defaults to: `null`.
  - name (String): Resource name of the repository, of the form &#x60;projects/&lt;project&gt;/repos/&lt;repo&gt;&#x60;.  The repo name may contain slashes. eg, &#x60;projects/myproject/repos/name/with/slash&#x60; Defaults to: `null`.
  - size (String): The disk usage of the repo, in bytes. Only returned by GetRepo. Defaults to: `null`.
  - url (String): URL to clone the repository from Google Cloud Source Repositories. Defaults to: `null`.
  """

  defstruct [
    :"mirrorConfig",
    :"name",
    :"size",
    :"url"
  ]
end

defimpl Poison.Decoder, for: GoogleApi.SourceRepo.V1.Model.Repo do
  import GoogleApi.SourceRepo.V1.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"mirrorConfig", :struct, GoogleApi.SourceRepo.V1.Model.MirrorConfig, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.SourceRepo.V1.Model.Repo do
  def encode(value, options) do
    GoogleApi.SourceRepo.V1.Deserializer.serialize_non_nil(value, options)
  end
end

