# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the elixir code generator program.
# Do not edit the class manually.

defmodule GoogleApi.Vault.V1.Model.DriveOptions do
  @moduledoc """
  Drive search advanced options

  ## Attributes

  - includeSharedDrives (boolean()): Set to true to include shared drive. Defaults to `nil`.
  - includeTeamDrives (boolean()): Set to true to include Team Drive. Defaults to `nil`.
  - versionDate (DateTime.t): Search the versions of the Drive file
  as of the reference date. These timestamps are in GMT and
  rounded down to the given date. Defaults to `nil`.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :includeSharedDrives => boolean(),
          :includeTeamDrives => boolean(),
          :versionDate => DateTime.t()
        }

  field(:includeSharedDrives)
  field(:includeTeamDrives)
  field(:versionDate, as: DateTime)
end

defimpl Poison.Decoder, for: GoogleApi.Vault.V1.Model.DriveOptions do
  def decode(value, options) do
    GoogleApi.Vault.V1.Model.DriveOptions.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.Vault.V1.Model.DriveOptions do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
