# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.DFAReporting.V4.Model.CampaignSummary do
  @moduledoc """
  Represents a summarized campaign information associated with this invoice.

  ## Attributes

  *   `billingInvoiceCode` (*type:* `String.t`, *default:* `nil`) - Campaign billing invoice code.
  *   `campaignId` (*type:* `String.t`, *default:* `nil`) - Campaign ID.
  *   `preTaxAmountMicros` (*type:* `String.t`, *default:* `nil`) - The pre-tax amount for this campaign, in micros of the invoice's currency.
  *   `taxAmountMicros` (*type:* `String.t`, *default:* `nil`) - The tax amount for this campaign, in micros of the invoice's currency.
  *   `totalAmountMicros` (*type:* `String.t`, *default:* `nil`) - The total amount of charges for this campaign, in micros of the invoice's currency.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :billingInvoiceCode => String.t() | nil,
          :campaignId => String.t() | nil,
          :preTaxAmountMicros => String.t() | nil,
          :taxAmountMicros => String.t() | nil,
          :totalAmountMicros => String.t() | nil
        }

  field(:billingInvoiceCode)
  field(:campaignId)
  field(:preTaxAmountMicros)
  field(:taxAmountMicros)
  field(:totalAmountMicros)
end

defimpl Poison.Decoder, for: GoogleApi.DFAReporting.V4.Model.CampaignSummary do
  def decode(value, options) do
    GoogleApi.DFAReporting.V4.Model.CampaignSummary.decode(value, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.DFAReporting.V4.Model.CampaignSummary do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
