# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.Dialogflow.V2.Model.GoogleCloudDialogflowV2DocumentReloadStatus do
  @moduledoc """
  The status of a reload attempt.

  ## Attributes

  *   `status` (*type:* `GoogleApi.Dialogflow.V2.Model.GoogleRpcStatus.t`, *default:* `nil`) - The status of a reload attempt or the initial load.
  *   `time` (*type:* `DateTime.t`, *default:* `nil`) - The time of a reload attempt. This reload may have been triggered automatically or manually and may not have succeeded.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :status => GoogleApi.Dialogflow.V2.Model.GoogleRpcStatus.t() | nil,
          :time => DateTime.t() | nil
        }

  field(:status, as: GoogleApi.Dialogflow.V2.Model.GoogleRpcStatus)
  field(:time, as: DateTime)
end

defimpl Poison.Decoder,
  for: GoogleApi.Dialogflow.V2.Model.GoogleCloudDialogflowV2DocumentReloadStatus do
  def decode(value, options) do
    GoogleApi.Dialogflow.V2.Model.GoogleCloudDialogflowV2DocumentReloadStatus.decode(
      value,
      options
    )
  end
end

defimpl Poison.Encoder,
  for: GoogleApi.Dialogflow.V2.Model.GoogleCloudDialogflowV2DocumentReloadStatus do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
