# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.Analytics.V3.Api.Data do
  @moduledoc """
  API calls for all endpoints tagged `Data`.
  """

  alias GoogleApi.Analytics.V3.Connection
  alias GoogleApi.Gax.{Request, Response}

  @doc """
  Returns Analytics data for a view (profile).

  ## Parameters

  - connection (GoogleApi.Analytics.V3.Connection): Connection to server
  - ids (String.t): Unique table ID for retrieving Analytics data. Table ID is of the form ga:XXXX, where XXXX is the Analytics view (profile) ID.
  - start_date (String.t): Start date for fetching Analytics data. Requests can specify a start date formatted as YYYY-MM-DD, or as a relative date (e.g., today, yesterday, or 7daysAgo). The default value is 7daysAgo.
  - end_date (String.t): End date for fetching Analytics data. Request can should specify an end date formatted as YYYY-MM-DD, or as a relative date (e.g., today, yesterday, or 7daysAgo). The default value is yesterday.
  - metrics (String.t): A comma-separated list of Analytics metrics. E.g., &#39;ga:sessions,ga:pageviews&#39;. At least one metric must be specified.
  - optional_params (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :dimensions (String.t): A comma-separated list of Analytics dimensions. E.g., &#39;ga:browser,ga:city&#39;.
    - :filters (String.t): A comma-separated list of dimension or metric filters to be applied to Analytics data.
    - :include-empty-rows (boolean()): The response will include empty rows if this parameter is set to true, the default is true
    - :max-results (integer()): The maximum number of entries to include in this feed.
    - :output (String.t): The selected format for the response. Default format is JSON.
    - :samplingLevel (String.t): The desired sampling level.
    - :segment (String.t): An Analytics segment to be applied to data.
    - :sort (String.t): A comma-separated list of dimensions or metrics that determine the sort order for Analytics data.
    - :start-index (integer()): An index of the first entity to retrieve. Use this parameter as a pagination mechanism along with the max-results parameter.

  ## Returns

  {:ok, %GoogleApi.Analytics.V3.Model.GaData{}} on success
  {:error, info} on failure
  """
  @spec analytics_data_ga_get(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          String.t(),
          String.t(),
          keyword()
        ) :: {:ok, GoogleApi.Analytics.V3.Model.GaData.t()} | {:error, Tesla.Env.t()}
  def analytics_data_ga_get(
        connection,
        ids,
        start_date,
        end_date,
        metrics,
        optional_params \\ [],
        opts \\ []
      ) do
    optional_params_config = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :dimensions => :query,
      :filters => :query,
      :"include-empty-rows" => :query,
      :"max-results" => :query,
      :output => :query,
      :samplingLevel => :query,
      :segment => :query,
      :sort => :query,
      :"start-index" => :query
    }

    request =
      Request.new()
      |> Request.method(:get)
      |> Request.url("/analytics/v3/data/ga")
      |> Request.add_param(:query, :ids, ids)
      |> Request.add_param(:query, :"start-date", start_date)
      |> Request.add_param(:query, :"end-date", end_date)
      |> Request.add_param(:query, :metrics, metrics)
      |> Request.add_optional_params(optional_params_config, optional_params)

    connection
    |> Connection.execute(request)
    |> Response.decode(opts ++ [struct: %GoogleApi.Analytics.V3.Model.GaData{}])
  end

  @doc """
  Returns Analytics Multi-Channel Funnels data for a view (profile).

  ## Parameters

  - connection (GoogleApi.Analytics.V3.Connection): Connection to server
  - ids (String.t): Unique table ID for retrieving Analytics data. Table ID is of the form ga:XXXX, where XXXX is the Analytics view (profile) ID.
  - start_date (String.t): Start date for fetching Analytics data. Requests can specify a start date formatted as YYYY-MM-DD, or as a relative date (e.g., today, yesterday, or 7daysAgo). The default value is 7daysAgo.
  - end_date (String.t): End date for fetching Analytics data. Requests can specify a start date formatted as YYYY-MM-DD, or as a relative date (e.g., today, yesterday, or 7daysAgo). The default value is 7daysAgo.
  - metrics (String.t): A comma-separated list of Multi-Channel Funnels metrics. E.g., &#39;mcf:totalConversions,mcf:totalConversionValue&#39;. At least one metric must be specified.
  - optional_params (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :dimensions (String.t): A comma-separated list of Multi-Channel Funnels dimensions. E.g., &#39;mcf:source,mcf:medium&#39;.
    - :filters (String.t): A comma-separated list of dimension or metric filters to be applied to the Analytics data.
    - :max-results (integer()): The maximum number of entries to include in this feed.
    - :samplingLevel (String.t): The desired sampling level.
    - :sort (String.t): A comma-separated list of dimensions or metrics that determine the sort order for the Analytics data.
    - :start-index (integer()): An index of the first entity to retrieve. Use this parameter as a pagination mechanism along with the max-results parameter.

  ## Returns

  {:ok, %GoogleApi.Analytics.V3.Model.McfData{}} on success
  {:error, info} on failure
  """
  @spec analytics_data_mcf_get(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          String.t(),
          String.t(),
          keyword()
        ) :: {:ok, GoogleApi.Analytics.V3.Model.McfData.t()} | {:error, Tesla.Env.t()}
  def analytics_data_mcf_get(
        connection,
        ids,
        start_date,
        end_date,
        metrics,
        optional_params \\ [],
        opts \\ []
      ) do
    optional_params_config = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :dimensions => :query,
      :filters => :query,
      :"max-results" => :query,
      :samplingLevel => :query,
      :sort => :query,
      :"start-index" => :query
    }

    request =
      Request.new()
      |> Request.method(:get)
      |> Request.url("/analytics/v3/data/mcf")
      |> Request.add_param(:query, :ids, ids)
      |> Request.add_param(:query, :"start-date", start_date)
      |> Request.add_param(:query, :"end-date", end_date)
      |> Request.add_param(:query, :metrics, metrics)
      |> Request.add_optional_params(optional_params_config, optional_params)

    connection
    |> Connection.execute(request)
    |> Response.decode(opts ++ [struct: %GoogleApi.Analytics.V3.Model.McfData{}])
  end

  @doc """
  Returns real time data for a view (profile).

  ## Parameters

  - connection (GoogleApi.Analytics.V3.Connection): Connection to server
  - ids (String.t): Unique table ID for retrieving real time data. Table ID is of the form ga:XXXX, where XXXX is the Analytics view (profile) ID.
  - metrics (String.t): A comma-separated list of real time metrics. E.g., &#39;rt:activeUsers&#39;. At least one metric must be specified.
  - optional_params (KeywordList): [optional] Optional parameters
    - :alt (String.t): Data format for the response.
    - :fields (String.t): Selector specifying which fields to include in a partial response.
    - :key (String.t): API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
    - :oauth_token (String.t): OAuth 2.0 token for the current user.
    - :prettyPrint (boolean()): Returns response with indentations and line breaks.
    - :quotaUser (String.t): An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
    - :userIp (String.t): Deprecated. Please use quotaUser instead.
    - :dimensions (String.t): A comma-separated list of real time dimensions. E.g., &#39;rt:medium,rt:city&#39;.
    - :filters (String.t): A comma-separated list of dimension or metric filters to be applied to real time data.
    - :max-results (integer()): The maximum number of entries to include in this feed.
    - :sort (String.t): A comma-separated list of dimensions or metrics that determine the sort order for real time data.

  ## Returns

  {:ok, %GoogleApi.Analytics.V3.Model.RealtimeData{}} on success
  {:error, info} on failure
  """
  @spec analytics_data_realtime_get(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, GoogleApi.Analytics.V3.Model.RealtimeData.t()} | {:error, Tesla.Env.t()}
  def analytics_data_realtime_get(connection, ids, metrics, optional_params \\ [], opts \\ []) do
    optional_params_config = %{
      :alt => :query,
      :fields => :query,
      :key => :query,
      :oauth_token => :query,
      :prettyPrint => :query,
      :quotaUser => :query,
      :userIp => :query,
      :dimensions => :query,
      :filters => :query,
      :"max-results" => :query,
      :sort => :query
    }

    request =
      Request.new()
      |> Request.method(:get)
      |> Request.url("/analytics/v3/data/realtime")
      |> Request.add_param(:query, :ids, ids)
      |> Request.add_param(:query, :metrics, metrics)
      |> Request.add_optional_params(optional_params_config, optional_params)

    connection
    |> Connection.execute(request)
    |> Response.decode(opts ++ [struct: %GoogleApi.Analytics.V3.Model.RealtimeData{}])
  end
end
