name: Generate-Updates
on:
  workflow_dispatch:
    inputs:
      args:
        description: "Extra command line arguments."
        required: false

jobs:
  generate-updates:
    if: ${{ github.repository == 'googleapis/elixir-google-api' }}
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
      APPROVAL_GITHUB_TOKEN: ${{secrets.YOSHI_APPROVER_TOKEN}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
      - name: Install Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "26.2.3"
          elixir-version: "1.14.5-otp-26"
          version-type: strict
      - name: Install tools
        run: "gem install --no-document toys"
      - name: execute
        run: |
          toys generate-updates -v --fork ${{ github.event.inputs.args }}
